import { defaultLocale, t } from '@/i18n';

const tr = (key: Parameters<typeof t>[1]) => t(defaultLocale, key);

export const momentsLabels = {
  allChannels: tr('moments.allChannels'),
  back: tr('moments.back'),
  channel: tr('moments.channel'),
  channelNavigation: tr('moments.channels'),
  cacheNotice: tr('moments.cacheNotice'),
  collapse: tr('moments.collapse'),
  revealSpoiler: tr('content.revealSpoiler'),
  copied: defaultLocale === 'en' ? 'Copied' : defaultLocale === 'ja' ? 'コピーしました' : '已复制',
  copyFailed: tr('moments.copyFailed'),
  copyLink: tr('moments.copyLink'),
  emptyChannel: tr('moments.emptyChannel'),
  emptyMessage: tr('moments.emptyMessage'),
  expand: tr('moments.expand'),
  feedUnavailable: tr('moments.unavailableDescription'),
  image: tr('moments.image'),
  mediaMore: tr('moments.mediaMore'),
  mediaMessage: tr('moments.mediaMessage'),
  mediaProcessing: tr('moments.mediaProcessing'),
  mediaUnavailable: tr('moments.mediaUnavailable'),
  newer: tr('moments.newer'),
  newest: tr('moments.newest'),
  noChannels: tr('moments.emptyChannels'),
  noResults: tr('moments.noResults'),
  notFound: tr('moments.notFound'),
  notFoundDescription: tr('moments.notFoundDescription'),
  older: tr('moments.older'),
  olderContent: tr('moments.loadEarlier'),
  loadingEarlier: tr('moments.loadingEarlier'),
  loadedEarlier: tr('moments.loadedEarlier'),
  allLoaded: tr('moments.allLoaded'),
  loadEarlierFailed: tr('moments.loadEarlierFailed'),
  openDocument: tr('moments.openDocument'),
  permalink: tr('moments.permalink'),
  pagination: tr('moments.pagination'),
  rateLimited: tr('moments.rateLimitedDescription'),
  rateLimitedTitle: tr('moments.rateLimited'),
  relevance: tr('moments.relevance'),
  retry: tr('moments.retry'),
  search: tr('moments.search'),
  searchForm: tr('moments.searchForm'),
  searchEmpty: tr('moments.searchEmpty'),
  searchHint: tr('moments.searchHint'),
  searchPlaceholder: tr('moments.searchPlaceholder'),
  searchQuery: tr('moments.searchQuery'),
  searchResults: tr('moments.searchResults'),
  searchTooLong: tr('moments.searchTooLong'),
  sort: tr('moments.sort'),
  submitSearch: tr('moments.search'),
  updated: tr('moments.updated'),
  unavailableTitle: tr('moments.unavailable'),
  contextNavigation: tr('moments.contextNavigation'),
  tags: tr('moments.tags'),
  video: tr('moments.video'),
  audio: tr('moments.audio'),
  document: tr('moments.document'),
  viewSource: tr('moments.viewSource'),
} as const;

export const cursorPaginationLabels = {
  next: momentsLabels.olderContent,
  back: momentsLabels.back,
  navigation: momentsLabels.pagination,
  loading: momentsLabels.loadingEarlier,
  loaded: momentsLabels.loadedEarlier,
  end: momentsLabels.allLoaded,
  error: momentsLabels.loadEarlierFailed,
  retry: momentsLabels.retry,
} as const;

export const messageCardLabels = {
  updated: momentsLabels.updated,
  permalink: momentsLabels.permalink,
  copyLink: momentsLabels.copyLink,
  copied: momentsLabels.copied,
  copyFailed: momentsLabels.copyFailed,
  viewSource: momentsLabels.viewSource,
  emptyMessage: momentsLabels.emptyMessage,
  expand: momentsLabels.expand,
  collapse: momentsLabels.collapse,
  revealSpoiler: momentsLabels.revealSpoiler,
  mediaProcessing: momentsLabels.mediaProcessing,
  mediaUnavailable: momentsLabels.mediaUnavailable,
  image: momentsLabels.image,
  video: momentsLabels.video,
  audio: momentsLabels.audio,
  document: momentsLabels.document,
  openDocument: momentsLabels.openDocument,
  mediaMore: momentsLabels.mediaMore,
  tags: momentsLabels.tags,
};
